[package]
edition = "2018"
name = "cloudflare-ddns"
version = "0.1.0"

[dependencies]
anyhow = "1.0"

tokio.version = "1.25"
tokio.features = ["fs", "macros"]

cloudflare = "0.10.1"

nix.version = "0.26"
nix.features = ["net", "socket"]
nix.default-features = false

argh = "0.1"

serde.version = "1.0"
serde.features = ["derive"]

toml = "0.7"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 'z'
lto = true
strip = true
panic = "abort"