[package]
edition = "2018"
name = "cloudflare-ddns-rs"
version = "0.1.0"

[dependencies]
clap = "3.0.0-beta.4"
cloudflare = {version = "0.8.6", features = ["rustls-tls"], default-features = false}
colored = "2.0.0"
nix = "0.23.0"
serde = {version = "1.0", features = ["derive"]}
toml = "0.5.8"
